### ISSUE TITLE
Grey color... No, please.

### ISSUE THREAD

**Issue by tkovs** [mstallone/Brainfuck#1]
BrainfuckInputLabel's color isn't so cool, must have a better color. White maybe..

![screen_2015-05-23_17-06-55](https://cloud.githubusercontent.com/assets/8717661/7785614/63170c82-0187-11e5-8cf4-984aadd378b4.png)

**Comment by mstallone** [comment]
To clarify, do you mean the background color or the text color itself?

**Comment by tkovs** [comment]
Background color.
